# Generated by Django 3.0.2 on 2020-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit',
            field=models.BooleanField(default='false'),
            preserve_default=False,
        ),
    ]
