# Generated by Django 3.0.2 on 2020-01-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='edit',
        ),
    ]
