# Generated by Django 3.0.2 on 2020-01-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200120_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='edit',
        ),
    ]
