# Generated by Django 3.0.2 on 2020-01-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
